### ISSUE TITLE
Having issues bundling zoneinfo files

### ISSUE THREAD

**Issue by Ruby-Newbie-85** [mhartl/rails_tutorial_6th_edition_gemfiles#12]
**What I wrote in VSCode (per instructions):**
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem 
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
end

**Result in terminal:**
$ bundle install

[!] There was an error parsing `Gemfile`: syntax error, unexpected local variable or method, expecting `end' -
. Bundler cannot continue.

 #  from C:/Users/wzuro/environment/hello_app/Gemfile:33
 #  -------------------------------------------
 #  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
 >  end #  source 'https://rubygems.org'

Any insight would be extremely helpful

**Comment by mhartl** [comment]
It looks like you have a superfluous `end` in your Gemfile. I suggest you remove it and see what happens.
