### ISSUE TITLE
Git-bash terminal

### ISSUE THREAD

**Issue by Ruby-Newbie-85** [mhartl/rails_tutorial_6th_edition_gemfiles#15]
Mr. Hartl,

I just want to thank you for helping me out with the issues I've been encountering.  Believe me, I am doing my best not to overwhelm you with inquiries.

For the purposes of completing your tutorial, am I ok with using Git Bash as my default terminal, or do you recommend I install the windows terminal and use that as my default terminal?

Thanks again.

**Comment by mhartl** [comment]
Thanks for your message. I’m not personally familiar with either of the things you mention, so I’m afraid I can’t be of much help here. Everything I know about dev environments can be found in [*Learn Enough Dev Environment to Be Dangerous*](https://www.learnenough.com/dev-environment-tutorial).
