### ISSUE TITLE
Precompiling assets failed.

### ISSUE THREAD

**Issue by osvfelices** [mhartl/rails_tutorial_6th_edition_gemfiles#16]
Hey when uploading the project into heroku I get this issue:

 Compiling...
remote:        Compilation failed:
remote:        yarn run v1.22.4
remote:        info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
remote:        
remote:        
remote:        error Command "webpack" not found.
remote:        
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to still-lake-83200.
remote: 
To https://git.heroku.com/still-lake-83200.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/still-lake-83200.git'

Any idea how to fix it?

**Comment by mhartl** [comment]
Thanks for your comment. I replied separately to your email, but I’ll note here that I recently (within the last couple of weeks) confirmed that the steps in the tutorial led to a successful deployment to Heroku from the Cloud9 IDE. I suggest retracing your steps to ensure that the tutorial is being followed exactly as written. I also recommend consulting the resources on the [Rails Tutorial Help page](https://www.railstutorial.org/help). Hope this helps!
