### ISSUE TITLE
Gem 'childprocess' (hello-app) issue

### ISSUE THREAD

**Issue by Ruby-Newbie-85** [mhartl/rails_tutorial_6th_edition_gemfiles#17]
Mr. Hartl,

This is the current issue I am having:
 
$ bundle update
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies...
Bundler could not find compatible versions for gem "childprocess":
  In Gemfile:
    childprocess (= 4.1.0)

    selenium-webdriver (= 3.142.7) was resolved to 3.142.7, which depends on
      childprocess (>= 0.5, < 4.0)

I attempted to add the 'childprocess' gem above 'selenium-driver', within the **group: test do**.  Do you propose I add the 'childprocess' gem within a different group of the Gemfile?

Thank you

**Comment by mhartl** [comment]
I haven’t seen this error before. Can you reproduce it using the [reference app](https://github.com/mhartl/sample_app_6th_ed)?

**Comment by dirschn** [comment]
I'm having this issue now too, if anyone's figured it out yet?

**Comment by dirschn** [comment]
I changed the childprocess version in Gemfile.lock from 4.1.0 to 3.0.0... it seems to have working properly since, though I'm not sure if that'll mess other things up later on.

**Comment by mhartl** [comment]
I’ll reiterate my question about the [reference app](https://github.com/mhartl/sample_app_6th_ed), whose Gemfile specifies that `selenium-webdriver` have version `3.142.7`. With that version number, the correct `childprocess` gem version should be installed automatically.

**Comment by dirschn** [comment]
So in order to reproduce this with reference app, do I clone that repo and attempt to install it the same as I did with my sample app?

**Comment by dirschn** [comment]
Using the [reference app](https://github.com/mhartl/sample_app_6th_ed), I was able to get past the bundle install/bundle update, but then I run into an issue where rails fails no matter what I try to do with it. This is what I get

`% rails -v
/usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/compile_cache/iseq.rb:13:in `to_binary': wrong argument type false (expected Symbol) (TypeError)
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/compile_cache/iseq.rb:13:in `input_to_storage'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/compile_cache/iseq.rb:30:in `fetch'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/compile_cache/iseq.rb:55:in `load_iseq'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
        from /home/nick/.local/share/gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:1:in `<main>'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/nick/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/command.rb:7:in `<main>'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/nick/.local/share/gem/ruby/3.0.0/gems/railties-6.1.4.1/lib/rails/commands.rb:3:in `<main>'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /home/nick/Transit/dev-training/ruby-on-rails-training/sample_app_6th_ed/bin/rails:9:in `<top (required)>'
        from /usr/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        from /usr/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        from /usr/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        from /usr/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        from /usr/lib/ruby/gems/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        from /usr/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        from /usr/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/nick/Transit/dev-training/ruby-on-rails-training/sample_app_6th_ed/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'`

**Comment by dirschn** [comment]
So I did some digging, in the reference one your Gemfile.lock has childprocess at 3.0.0, while the Gemfile.lock has childprocess 4.1.0. So it seems that is what I should have done, though I don't know why they would be different... I'm still very unfamiliar with all this stuff. So that settles the issue with selenium-webdriver and childprocess, I guess.

**Comment by mhartl** [comment]
It looks like the versions got out of sync somehow. Try `gem uninstall childprocess` and `bundle install` to install compatible versions of `selenium-webdriver` and `childprocess`.

**Comment by dirschn** [comment]
It wouldn't let me uninstall childprocess, both as root and normal user. The error code didn't tell me why. I just manually changed the Gemfile.lock to read `childprocess (3.0.0)` which caused `bundle update` to finally pass. I am, however, having that (potentially) unrelated issue with rails itself. Should I open a separate thread? Or is it not related to your tutorial?

**Comment by dirschn** [comment]
Never mind, somehow I fixed it. No idea what I did, but everything seems to be working properly now. Thanks for your help
