### ISSUE TITLE
Rails generate scaffold issue (Toy app)

### ISSUE THREAD

**Issue by Ruby-Newbie-85** [mhartl/rails_tutorial_6th_edition_gemfiles#18]
$ rails generate scaffold User name:string email:string
      invoke  active_record
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/application/configuration.rb:290:in `database
_configuration': Cannot load database configuration: (RuntimeError)
Could not load database configuration. No such file - ["config/database.yml"]
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/railtie.rb:221:in `b
lock (2 levels) in <class:Railtie>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:71:in `class_eval'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:71:in `block in execute_hook'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:61:in `with_execution_control'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:66:in `execute_hook'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:52:in `block in run_load_hooks'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:51:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:51:in `run_load_hooks'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/base.rb:315:in `<mod
ule:ActiveRecord>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/base.rb:15:in `<main
>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:23:in `block in require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features
_index.rb:92:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:31:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/generators/named_base.rb:197:in
`pluralize_table_names?'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/generators/named_base.rb:88:in `
table_name'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/rails/generators/active_record/mod
el/model_generator.rb:23:in `create_migration_file'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_a
ll'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:277:in `block in _invoke_for_c
lass_method'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/shell.rb:68:in `with_padding'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:266:in `_invoke_for_class_meth
od'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:134:in `_invoke_from_option_or
m'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_a
ll'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/generators.rb:275:in `invoke'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/generate/generate_comma
nd.rb:26:in `perform'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command/base.rb:69:in `perform'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command.rb:48:in `invoke'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:23:in `block in require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features
_index.rb:92:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:31:in `require'
        from bin/rails:4:in `<main>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/application/configuration.rb:290:in `database
_configuration': Could not load database configuration. No such file - ["config/database.yml"] (RuntimeError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/railtie.rb:221:in `b
lock (2 levels) in <class:Railtie>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:71:in `class_eval'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:71:in `block in execute_hook'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:61:in `with_execution_control'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:66:in `execute_hook'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:52:in `block in run_load_hooks'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:51:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/lazy_load_hooks.rb
:51:in `run_load_hooks'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/base.rb:315:in `<mod
ule:ActiveRecord>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/base.rb:15:in `<main
>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:23:in `block in require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features
_index.rb:92:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:31:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/generators/named_base.rb:197:in
`pluralize_table_names?'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/generators/named_base.rb:88:in `
table_name'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/rails/generators/active_record/mod
el/model_generator.rb:23:in `create_migration_file'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_a
ll'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:277:in `block in _invoke_for_c
lass_method'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/shell.rb:68:in `with_padding'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:266:in `_invoke_for_class_meth
od'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:134:in `_invoke_from_option_or
m'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `block in invoke_a
ll'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `map'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:134:in `invoke_all'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/group.rb:232:in `dispatch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/generators.rb:275:in `invoke'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/commands/generate/generate_comma
nd.rb:26:in `perform'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command/base.rb:69:in `perform'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/command.rb:48:in `invoke'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:23:in `block in require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features
_index.rb:92:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel
_require.rb:31:in `require'
        from bin/rails:4:in `<main>'

Any suggestions?
Thanks

**Comment by mhartl** [comment]
It looks like the `database.yml` file generated automatically by `rails new` is somehow missing. I suggest retracing your steps, taking care to run `ls config/database.yml` to make sure the file is still there at each step.

If you require additional assistance, please consult the [Rails Tutorial Help page](https://www.railstutorial.org/help) for more information.
