### ISSUE TITLE
pg'1.2.3' issue

### ISSUE THREAD

**Issue by Ruby-Newbie-85** [mhartl/rails_tutorial_6th_edition_gemfiles#19]
**STEP 1**
$ bundle install
[DEPRECATED] This Gemfile does not include an explicit global source. Not using
an explicit global source may result in a different lockfile being generated dep
ending on the gems you have installed locally before bundler is run. Instead, de
fine a global source in your Gemfile like this: source "https://rubygems.org".
Could not find gem 'pg (= 1.2.3)' in locally installed gems.

**STEP 2**
$ gem install pg -v'1.2.3'
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pg-1.2.3/ext
C:/Ruby30-x64/bin/ruby.exe -I C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0 -r ./siteco
nf20220208-13768-r2aq.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby30-x64/bin/$(RUBY_BASE_NAME)
        --with-pg
        --without-pg
        --enable-windows-cross
        --disable-windows-cross
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can
 be found here:

  C:/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/pg-1.2.3/mkmf.l
og

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/pg-1.2
.3 for inspection.
Results logged to C:/Ruby30-x64/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0
/pg-1.2.3/gem_make.out

**STEP 3**
 gem install pg '1.2.3' --with-pg-config=/path/to/pg_config
ERROR:  While executing gem ... (Gem::OptionParser::InvalidOption)
    invalid option: --with-pg-config=C:/Program Files/Git/path/to/pg_config

I also tried running a couple of the other commands that were suggested.  Do you have any recommendations on how to proceed further?

Thank you

**Comment by mhartl** [comment]
Thanks for reaching out. Unfortunately, it’s practically impossible to debug issues like this remotely. The term “technical sophistication” was basically invented to cover cases such as this.

One thing I can suggest is to use the exact gems and commands used in the tutorial. In other words, use `bundle _2.2.17_ install` instead of `bundle install`. That will ensure that any unexpected behavior isn’t the result of version incompatibilities.
