### ISSUE TITLE
Issue with Guard and Pry

### ISSUE THREAD

**Issue by Charcuchet** [mhartl/rails_tutorial_6th_edition_gemfiles#2]
In section 3.6 of the latest version of the Rails Tutorial, Guard doesn't install properly. 

On launch there is an error "/home/ubuntu/.rvm/gems/ruby-2.6.3/gems/guard-2.15.0/lib/guard/jobs/pry_wrapper.rb:131:in `_setup': undefined method `file=' for #<Pry::History:0x000056258cb81728>"

It seems to be linked to https://github.com/guard/guard/issues/953. 

It can be fixed by using the latest release of Guard 2.16.2.

**Comment by mhartl** [comment]
Thanks! I’ve updated the tutorial accordingly.
