### ISSUE TITLE
Webpack doesn't compile -- solution

### ISSUE THREAD

**Issue by jaduret** [mhartl/rails_tutorial_6th_edition_gemfiles#20]
Webpack compile error when deploying to heroku
--------------------------------------------------
Whilst I had an all green install for webpack, it was silently failing preventing the heroku deployment in the first chapter of the book. After a lot of digging I found the following solution that i though is worst sharing. The issue lining to a certificate mismatch. Solution is:

_dig https://registry.npmjs.org/webpack @1.1.1.1
bundle update
bundle install without --production_

This is to be done before git push heroku master

**Comment by mhartl** [comment]
Thanks for the heads-up. I recently went through a full deployment of the initial “hello app”, as you can see in [this short video](https://youtu.be/HUXFnd6vl7s), and didn’t run into the problem you describe. I’ll keep an eye on it, though, and will plan to update the tutorial if necessary. In any case, Rails 7 has removed the Webpack dependency, so this problem will go away as soon as the new edition is finished.
