### ISSUE TITLE
web-console version causing exception page issue

### ISSUE THREAD

**Issue by lewispb** [mhartl/rails_tutorial_6th_edition_gemfiles#5]
In the hello_app gemfile, using web-console 4.0.2 disables the default rails exception page (containing helpful error information) and instead shows the generic Rails "We're sorry, but something went wrong" that is usually only shown in production.

To reproduce simply follow the tutorial but raise an error inside of ApplicationController#hello.

Upgrading to web-console 4.1.0 resolves this issue.

**Comment by mhartl** [comment]
Great, thanks! I’ve updated the tutorial accordingly.

**Comment by Jaedwin** [comment]
> In the hello_app gemfile, using web-console 4.0.2 disables the default rails exception page (containing helpful error information) and instead shows the generic Rails "We're sorry, but something went wrong" that is usually only shown in production.
> 
> To reproduce simply follow the tutorial but raise an error inside of ApplicationController#hello.
> 
> Upgrading to web-console 4.1.0 resolves this issue.

Thank you! I was trying to figure out what was going on. Looks like I pulled a version of the gemfile a few days before web-console was updated to 4.1.0
