### ISSUE TITLE
pg-1.2.3 installation issues

### ISSUE THREAD

**Issue by iv41879** [mhartl/rails_tutorial_6th_edition_gemfiles#6]
Dear @mhartl 

I am enjoying reading your book I bought from Amazon - good job. 😃 
But I got some issue... please check if you have some time.

So when running `bundle update` (just before running `bundle install`) on Gem file from `hello_app` using `Cloud9` I get following error:

```
An error occurred while installing pg (1.2.3), and Bundler cannot continue.
Make sure that `gem install pg -v '1.2.3' --source 'https://rubygems.org/'` succeeds before bundling.
```

After running the command above I got this:

```
ubuntu:~/environment/hello_app (master) $ gem install pg -v '1.2.3' --source 'https://rubygems.org/'
Building native extensions. This could take a while...
ERROR:  Error installing pg:
        ERROR: Failed to build gem native extension.

    current directory: /home/ubuntu/.rvm/gems/ruby-2.6.3/gems/pg-1.2.3/ext
/home/ubuntu/.rvm/rubies/ruby-2.6.3/bin/ruby -I /home/ubuntu/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0 -r ./siteconf20201224-14941-19gf9mk.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/ubuntu/.rvm/rubies/ruby-2.6.3/bin/$(RUBY_BASE_NAME)
        --with-pg
        --without-pg
        --enable-windows-cross
        --disable-windows-cross
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ubuntu/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/2.6.0/pg-1.2.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/ubuntu/.rvm/gems/ruby-2.6.3/gems/pg-1.2.3 for inspection.
Results logged to /home/ubuntu/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/2.6.0/pg-1.2.3/gem_make.out
```

**Comment by iv41879** [comment]
Hm ok... maybe you could add the same statement for bundle install inside hello_app as with toy_app:
`bundle install --without production`

**Comment by mhartl** [comment]
You mean like [Listing 1.19](https://www.learnenough.com/ruby-on-rails-6th-edition-tutorial/beginning/deploying/heroku_setup#code-bundle_without_production)? 😉

<img width="751" alt="Screen Shot 2020-12-26 at 10 04 16 AM" src="https://user-images.githubusercontent.com/6232/103156825-c5270280-4761-11eb-9cf8-9d4ee7cc9ba1.png">

**Comment by iv41879** [comment]
@mhartl Yeah 👍 
Also inside Listing 3.5 I guess we should have `render html: ...` instead of `render text: ...` ?

**Comment by mhartl** [comment]
This is just because you have the print version, which always lags a little behind the online version I maintain. As you can see, the online version of [Listing 3.5](https://www.learnenough.com/ruby-on-rails-6th-edition-tutorial/static_pages/sample_app_setup#code-hello_action_redux_2) does use `render html: ...` as you suggest:

<img width="750" alt="Screen Shot 2020-12-26 at 10 50 46 AM" src="https://user-images.githubusercontent.com/6232/103157510-47b2c080-4768-11eb-9b40-f1d883bbc890.png">
